### PR TITLE
Add 3 cafes in Shanghai

### PR DESCRIPTION
**Pull request by ryaneof**
- Costa (Global Harbor)
- SeeSaw (淮海 755)
- Costa (九六广场)

### CODE REVIEW

**Comment by xhacker** [comment]
3️⃣☕️😋

**Comment by xhacker** [comment]
Sorry, made a mistake. Can you pr again?

**Comment by xhacker** [comment]
And you add adding 5 right? There should be 31 for Shanghai in total then.

**Comment by ryaneof** [comment]
@xhacker I'm adding 3 cafes, it suppose to be 29?

**Comment by xhacker** [comment]
@ryaneof: Oh right, should be 29.

**Pull request merged**
