### PR TITLE
Add: Maan Coffee @ Chongqing MixC / 星巴克 Starbucks @ 重庆袁家岗K-Land店

### PR DESCRIPTION
**Pull request by loicpirez**
Hello,
This is my contribution to this repository.
Please find an entry for Chongqing GeoJSON with Maan Coffee 漫咖啡 of Chongqing added.
I might record more later of Chongqing as this repository is really lacking information about this province. 😄 
Thank you.

Note: the latitude and longitude were retrieved using online Chinese maps.

### CODE REVIEW

**Comment by xavierchow** [comment]
@loicpirez hi, thanks for your RP!
I think you need to update the README markdown file as well as there is a total store number for Chongqing there.

**Comment by loicpirez** [comment]
Sorry my bad. Just updated it !

I have a suggestion for this repository: why not create a Google "MyMaps" maps from the GeoJSON available in this repository ?

**Comment by xavierchow** [comment]
Thank you for the udpate.

> I have a suggestion for this repository: why not create a Google "MyMaps" maps from the multiple GeoJSON available in this repository ?

I believe this repo is mainly as a collected data source instead of a presentation application?
summoning @xhacker for further explanation.

**Comment by loicpirez** [comment]
> I believe this repo is mainly as a collected data source instead of a presentation application?

It is indeed ! But I was just suggesting as a side-project maybe, using those collected data to a make a real Google Maps which could be added as a link in the README ?

**Comment by loicpirez** [comment]
Updated pull request by adding 星巴克 Starbucks (袁家岗K-Land店) with Google Map data.

**Comment by xhacker** [comment]
Thanks for the contribution!

**Pull request merged**
