### PR TITLE
- add Coffee Holic at Beijing

### PR DESCRIPTION
**Pull request by hit1024**

### CODE REVIEW

**Comment by xavierchow** [comment]
@hit1024 thanks, can you squash these commits? You can use `git rebase -i HEAD~2` or whatever.

**Comment by hit1024** [comment]
In fact, i chose a hard way: remove my old code and fork from the latest commit, and then i committed new code. #72 is the bad pull request.

Please check the diff, you'll see it.

Sorry for the confusing...😂

**Comment by xhacker** [comment]
@xavierchow: You can try the “Squash and merge” button.


@hit1024: Can you clean up the commit message a bit? I’d use something like “Add Coffee Holic at Beijing”.

**Comment by hit1024** [comment]
@xavierchow @xhacker thank you for your advice!

Commits are rebased now.

**Comment by xavierchow** [comment]
@xhacker I never know the merge option before, 👍

**Pull request merged**
