### PR TITLE
More helpful README

### PR DESCRIPTION
**Pull request by RYOHOI**
Easier way to acquire net speed & geo info

### CODE REVIEW

**Comment by xhacker** [comment]
Can you rebase so that the pull request only contains the current changes?

**Comment by HarukaMa** [comment]
把 speedtest.cn 叫做“Speedtest 中国站”并不妥，因为它和 speedtest.net 是完全不同的两个网站。
虽然看上去不影响测速结果准确性……（未测试

**Comment by xavierchow** [comment]
* Don't like the websites
* The commits are in a mess.

Closing.

**Comment by HarukaMa** [comment]
@RYOHOI : Try to do exactly one thing in one PR. It would be better if you open another PR to contribute those cafe.

**Comment by xavierchow** [comment]
The cafes in this PR have already been in [shenzhen.geojson](https://raw.githubusercontent.com/ElaWorkshop/awesome-cn-cafe/master/shenzhen.geojson)

**Pull request closed without merging**
