### PR TITLE
Set speedtest app as the recommended way to get speed and coordinates in mobile

### PR DESCRIPTION
**Pull request by crispgm**
#60

### CODE REVIEW

**Comment by AquarHEAD** [comment]
Can you cleanup your commits? Please rebase to master first.

**Comment by crispgm** [comment]
@AquarHEAD OK, but I don't know exactly why commits of former PRs always occur on my PR. Is there something I did wrong with the master on my forked repo?

**Comment by AquarHEAD** [comment]
@crispgm you need to make whichever branch you're submitting PR from even with the branch you're submitting to, in this case that's `crispgm:speedtestapp` and `ElaWorkshop:master` respectively.

It seems your `master` is also ahead of this repo, I have no idea why but I think it's definitely causing some problems.

**Comment by crispgm** [comment]
@aquarhead Yes, I notice that and synced again, but git said ```Everything up-to-date```.

And the commits cannot be rebased. Otherwise, this PR will cause a conflict. Any ideas with this situation? To delete my forked repo and fork again?

**Comment by xhacker** [comment]
@crispgm: You should always keep your `master` exactly the same with our `master`. (If your `master` is already messed up, maybe delete the whole thing and start over.) Then, whenever you want to make a change, run

```
# Make sure master is in sync with upstream
git pull upstream master

# Create a new branch derived from master
git checkout -b <new-feature-branch>
```

Then add pull request from `<new-feature-branch>`.

**Comment by crispgm** [comment]
@xhacker I used to develop on master in the past. But I strictly followed the flow this time. I synced the forked repo by:
```
git fetch upstream
git checkout master
git merge upstream/master
```
Now, git says ```Everything up-to-date```. However, GitHub prompts ```This branch is 6 commits ahead of ElaWorkshop:master.```.

It might be something wrong with the rebase problem in my last PR. So let me close and redo the whole thing?

**Comment by xhacker** [comment]
@crispgm: Yeah, your `master` is already ahead of upstream. Instead of redoing the whole thing, you can also remember the hash of your commit, and:

```
git checkout master

# Force reset your master to upstream’s
git reset --hard upstream/master

git checkout -b <new-feature-branch>
git cherry-pick <the-hash-you-remembered>
```

**Comment by xhacker** [comment]
Closing since this pr is messed up.

**Comment by crispgm** [comment]
@xhacker Thanks.

**Pull request closed without merging**
