### PR TITLE
Update chengdu.geojson

### PR DESCRIPTION
**Pull request by kid1412621**
add grok coffee

### CODE REVIEW

**Comment by xhacker** [comment]
Can you update the number in `README.md`?

**Comment by kid1412621** [comment]
> Can you update the number in `README.md`?

updated, why ci failed btw

**Comment by xhacker** [comment]
> > Can you update the number in `README.md`?
> 
> updated, why ci failed btw

CI failed because number wasn’t updated 😂

**Comment by xhacker** [comment]
Thank you!

**Comment by kid1412621** [comment]
> > > Can you update the number in `README.md`?
> > 
> > 
> > updated, why ci failed btw
> 
> CI failed because number wasn’t updated 😂

my bad, haha. actually I inspired by this repo then set up [a similar one about public library](https://github.com/kid1412621/CHN-Public-Library). I wish it could become helpful as this one.

**Pull request merged**
